---
abstract: 'Base class for Sys::Info'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  Test::More: 0.40
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Info-Base
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Sys::Info::Base:
    file: lib/Sys/Info/Base.pm
    version: 0.78
  Sys::Info::Constants:
    file: lib/Sys/Info/Constants.pm
    version: 0.78
  Sys::Info::Device:
    file: lib/Sys/Info/Device.pm
    version: 0.78
  Sys::Info::Device::CPU:
    file: lib/Sys/Info/Device/CPU.pm
    version: 0.78
  Sys::Info::Driver:
    file: lib/Sys/Info/Driver.pm
    version: 0.78
  Sys::Info::OS:
    file: lib/Sys/Info/OS.pm
    version: 0.78
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-sys-info-base/
version: 0.78
